config/routes.rb
Rails.application.routes.draw do
  get "sign_in", to: "users#sign_in"
  get "user_logout", to: "users#user_logout"
  # resources :users, only: [:show, :create, :new]
  resources :users
  resources :events
  resources :sign_in
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :creator_events, class_name: 'Event', foreign_key: 'creator_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

    def new
      @event = Event.new
    end

    def create
      # @current_user = session[:current_user]
      # @event = Event.User.build(event_params)
      # @post = current_user.posts.build(post_params)
      @event = current_user.creator_events.build(event_params)

      # @event.creator = session[:current_user]
      # @event.save
      if @event.save
        redirect_to events_path
      end
    end

  def current_user
    current_user = User.find_by(username: session[:current_user])
    current_user
  end

    private

    def event_params
        params.require(:event).permit(:event)
    end
end

app/controllers/sign_in_controller.rb
class SignInController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    end
  end

  def sign_in
    # @user = User.where("username like ?", "#{params[:username]}")
    @user = User.find_by(username: params[:username])
    if @user
      session[:current_user] = @user.username
      session[:current_user_id] = @user.id

    end
  end

  def user_logout
    session.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<% @events.each do |x| %>
  <%= link_to x.event, event_path(x) %> <br />
<% end %>

app/views/events/new.html.erb
<%= form_for(@event) do |f| %>
    <%= f.text_area :event %>
    <%= f.submit 'Submit' %>
<% end %>

app/views/events/show.html.erb
<%= @event.creator_id %> <br />
<%= link_to "All Events", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if flash[:now] %>
      <p class="alert"><%= error %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% if session[:current_user] %>
<%= link_to session[:current_user], user_path(session[:current_user_id]) %>
  <%= link_to "Logout", user_logout_path %>
<%else %>
  <%= link_to "Login", sign_in_path %>
<%end %>

<%= link_to 'New Events', new_event_path %>

app/views/users/new.html.erb
<%= form_for(@user) do |t| %>
  <%= t.label :username, 'Please Enter Username' %>
  <%= t.text_field :username %>
  <%= t.label :email, 'Please Enter Email' %>
  <%= t.email_field :email %>
  <%= t.submit 'Sign Up' %>
<% end %>

app/views/users/show.html.erb
<% @user.creator_events.each do |c| %>
  <%= c.creator_id %> <br />
<%= c.event %> <br />
  <%end %>
<%= link_to "Index Page", users_path %>

app/views/users/sign_in.html.erb
<% if session[:current_user] %>
  <%= session[:current_user] %>
  <%= link_to "Logout", user_logout_path %>
<%else %>
  <%= form_tag sign_in_path, :method => 'get' do %>
    <%= label_tag :username, 'Please enter Username' %>
    <%= text_field_tag :username, params[:username] %>
    <%= submit_tag "Login" %>
  <% end %>
<% end %>